### PR TITLE
relax R 3.5 requirement (qs v0.24.1)

### PR DESCRIPTION
**Pull request by traversc**
Tested (testthat) with R 3.3.3 on windows.

### CODE REVIEW

**Comment by hadley** [comment]
Looks like there's a stringfish issue?

```
OE> In file included from sf_functions.cpp:75:0:
OE> sf_disabled.h:19:154: error: ISO C++ forbids declaration of ‘sf_writeLines’ with no type [-fpermissive]
OE>  sf_writeLines(SEXP text, const std::string file, const std::string sep = "\n", const std::string na_value = "NA", const std::string encode_mode = "UTF-8") {NO_ALTREP_SUPPORT();}
```

**Comment by traversc** [comment]
Sorry about that, didn't show up on Windows. I'm going to see if I can set up multiple builds CodeCov or Travis and re-submit to CRAN.

**Comment by traversc** [comment]
Okay, attempt number 2. I fixed the issues in the stringfish package on CRAN and re-ran the github actions test on the fork. Hopefully good to go this time!

**Comment by hadley** [comment]
Guess I forgot to close this earlier; multidplyr looks like it works on 3.4 and up right now.
